/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bo.edu.uagrm.ficct.proyecto_grafo;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TabableView;

/**
 *
 * @author hp
 */
public class Proyecto extends javax.swing.JFrame {

    private DigrafoPesado migrafo;
    private boolean controlOrigen;
    private boolean controlDestino;
    List<String> posiciones;

    /**
     * Creates new form Grafo
     */
    public Proyecto() throws ExceptionesNroVerticeInvalidos, ExceptionAristaYaExiste, ExceptionAristaNoExiste {

        initComponents();

        controlOrigen = false;
        controlDestino = false;

        posiciones = new ArrayList<>();
        posiciones.add("LA PAZ");
        posiciones.add("BENI");
        posiciones.add("COCHABAMBA");
        posiciones.add("SANTA CRUZ");
        posiciones.add("PANDO");
        posiciones.add("CHUQUISACA");
        posiciones.add("ORURO");
        posiciones.add("POTOSI");
        posiciones.add("TARIJA");
        migrafo = new DigrafoPesado(posiciones.size());
        ///  del lapaz
        migrafo.insertarArista(0, 1, 100.0);
        migrafo.insertarArista(0, 6, 200.0);
        migrafo.insertarArista(1, 0, 400.0);
        migrafo.insertarArista(1, 4, 150.0);
        migrafo.insertarArista(1, 3, 200.0);
        migrafo.insertarArista(2, 6, 400.0);
        migrafo.insertarArista(2, 3, 250.0);
        migrafo.insertarArista(3, 2, 300.0);
        migrafo.insertarArista(3, 5, 350.0);
        migrafo.insertarArista(3, 1, 200.0);
        migrafo.insertarArista(4, 1, 100.0);
        migrafo.insertarArista(5, 8, 100.0);
        migrafo.insertarArista(5, 6, 250.0);
        migrafo.insertarArista(5, 3, 300.0);
        migrafo.insertarArista(6, 0, 500.0);
        migrafo.insertarArista(6, 2, 200.0);
        migrafo.insertarArista(6, 7, 200.0);
        migrafo.insertarArista(7, 6, 220.0);
        migrafo.insertarArista(7, 8, 100.0);
        migrafo.insertarArista(8, 7, 150.0);
        migrafo.insertarArista(8, 5, 200.0);
        mostraMatriz();

    }

    private void mostraMatriz() throws ExceptionAristaNoExiste {
        int n = AdyacenciaConPeso.getColumnCount();
        Double m[][] = new Double[n][n];
        for (int i = 0; i < migrafo.cantidadDeVertices(); i++) {
            for (int j = 0; j < migrafo.cantidadDeVertices(); j++) {
                m[i][j] = 0.0;
            }
        }
        for (int i = 0; i < n; i++) {
            Iterable<Integer> lista = migrafo.adyacentesDelVertice(i);
            for (Integer j : lista) {
                m[i][j] = migrafo.peso(i, j);
            }

        }
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                if (i == j) {
                    AdyacenciaConPeso.setValueAt(0 + "Bs", i, j);
                } else {
                    if (!migrafo.existeAdyacencia(i, j)) {
                        AdyacenciaConPeso.setValueAt("    °°", i, j);
                    } else {
                        AdyacenciaConPeso.setValueAt(m[i][j] + "Bs", i, j);

                    }
                }

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboOrigen = new javax.swing.JComboBox<>();
        comboDestino = new javax.swing.JComboBox<>();
        labelOrigen = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        btnCalcularCosto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AdyacenciaConPeso = new javax.swing.JTable();
        btnEliminarCamino = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAMINOS MAS CORTOS EN BOLIIA");
        setLocation(new java.awt.Point(5, -1));

        labelTitulo.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        labelTitulo.setText("CAMINOS MAS CORTOS");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("ciudades: ");

        comboOrigen.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        comboOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LA PAZ", "BENI", "COCHABAMBA", "SANTA CRUZ", "PANDO", "CHUQUISACA", "ORURO", "POTOSI", "TARIJA" }));
        comboOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrigenActionPerformed(evt);
            }
        });

        comboDestino.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        comboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LA PAZ", "BENI", "COCHABAMBA", "SANTA CRUZ", "PANDO", "CHUQUISACA", "ORURO", "POTOSI", "TARIJA" }));
        comboDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDestinoActionPerformed(evt);
            }
        });

        labelOrigen.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelOrigen.setText("ORIGEN");

        labelDestino.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        labelDestino.setText("DESTINO");

        label11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label11.setText("LA PAZ");

        label12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label12.setText("BENI");

        label13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label13.setText("COCHABAMBA");

        label14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label14.setText("SANTA CRUZ");

        label15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label15.setText("PANDO");

        label16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label16.setText("CHUQUISACA");

        label17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label17.setText("ORURO");

        label18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label18.setText("POTOSI");

        label19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label19.setText("TARIJA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnCalcularCosto.setText("CALCULAR COSTO");
        btnCalcularCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCostoActionPerformed(evt);
            }
        });

        AdyacenciaConPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AdyacenciaConPeso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "LA PAZ", "BENI", "COCHABAMBA", "SANTA CRUZ", "PANDO", "CHUQUISACA", "ORURO", "POTOSI", "TARIJA"
            }
        ));
        AdyacenciaConPeso.setRowHeight(53);
        AdyacenciaConPeso.setShowGrid(true);
        jScrollPane2.setViewportView(AdyacenciaConPeso);

        btnEliminarCamino.setText("ELIMINAR CAMINO");
        btnEliminarCamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCaminoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(306, 306, 306)
                                .addComponent(labelOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(labelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCalcularCosto)
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarCamino, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1988, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelOrigen)
                            .addComponent(comboOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDestino)
                            .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularCosto)
                    .addComponent(btnEliminarCamino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(434, 434, 434))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrigenActionPerformed

        controlOrigen = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOrigenActionPerformed

    private void btnCalcularCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCostoActionPerformed

        if (controlOrigen) {
            if (controlDestino) {
                String verticeOrigen = comboOrigen.getSelectedItem().toString();
                String verticeDestino = comboDestino.getSelectedItem().toString();
                int posOrigen = posiciones.indexOf(verticeOrigen);
                int posDestino = posiciones.indexOf(verticeDestino);
                try {
                    String inf = evaluarCamino(posOrigen, posDestino);
                    JOptionPane.showMessageDialog(null, inf, "INFORMACION DE CAMINOS ", HEIGHT);

                } catch (ExceptionAristaNoExiste ex) {
                    Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, "No existe arista", ex);
                }
                System.out.println("Es el origen" + posOrigen);
                System.out.println("Es el destino" + posDestino);

            } else {
/// dedstino no asido seleccionado
                JOptionPane.showMessageDialog(null, " SELECCIONE SU DESTINO", "INFORMACION ", HEIGHT);

            }
        } else {
///origen no a sido seleccionado
            JOptionPane.showMessageDialog(null, " SELECCIONE SU ORIGEN DE PARTIDA", "INFORMACION", HEIGHT);

        }
        String verticeOrigen = comboOrigen.getSelectedItem().toString();
        String verticeDestino = comboDestino.getSelectedItem().toString();

// TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularCostoActionPerformed
    private String evaluarCamino(int posOrigen, int PosDestino) throws ExceptionAristaNoExiste {
        Dijkstra camino = new Dijkstra(migrafo);
        String inf = "[ ";
        List<Integer> listaDeCaminos = camino.caminosMasCortos(posOrigen, PosDestino);
        for (Integer pos : listaDeCaminos) {
            inf += " -- " + posiciones.get(pos);

        }
        inf += " --] CON UN COSTO DE :" + camino.obtenerCosto();
        return inf;
    }
    private void comboDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDestinoActionPerformed
        controlDestino = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDestinoActionPerformed

    private void btnEliminarCaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCaminoActionPerformed
        String verticeOrigen = comboOrigen.getSelectedItem().toString();
        String verticeDestino = comboDestino.getSelectedItem().toString();

        int confirmado = JOptionPane.showConfirmDialog(
                null,
                " ¿estas seguro de elimiar el camino de: "+verticeOrigen+" a "+verticeDestino+" ?");
        if (JOptionPane.OK_OPTION == confirmado) {
            int posOrigen= posiciones.indexOf(verticeOrigen);
            int posDestino= posiciones.indexOf(verticeDestino);
            if (migrafo.existeAdyacencia(posOrigen, posDestino)) {
                try {
                migrafo.elimnarArista(posOrigen, posDestino);
                mostraMatriz();
                JOptionPane.showMessageDialog(null, " Se Elimino el camino de"+verticeOrigen+" a "+verticeDestino , "INFORMACION", HEIGHT);

            } catch (ExceptionAristaNoExiste ex) {
                Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, "No se logro eliminar", ex);
            } 
            }else{
                JOptionPane.showMessageDialog(null, "No existe camino de"+verticeOrigen+" a "+verticeDestino , "INFORMACION", HEIGHT);

            }
           

        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCaminoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Proyecto().setVisible(true);
                } catch (ExceptionesNroVerticeInvalidos ex) {
                    Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, " hay problemas con el grafo", ex);
                } catch (ExceptionAristaYaExiste ex) {
                    Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExceptionAristaNoExiste ex) {
                    Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AdyacenciaConPeso;
    private javax.swing.JButton btnCalcularCosto;
    private javax.swing.JButton btnEliminarCamino;
    private javax.swing.JComboBox<String> comboDestino;
    private javax.swing.JComboBox<String> comboOrigen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelOrigen;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
